#+TITLE:       About Me and Amanokami
#+AUTHOR:      Paul Elder
#+EMAIL:       paul.elder@amanokami.net
#+DATE:        2016-02-29 Mon
#+URI:         /about/
#+KEYWORDS: 
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+DESCRIPTION: About Me and Amanokami (hey it rhymes!)

* About Me

I am Paul Elder, an (almost done) IB diploma candidate in Japan.

My system is a Lenovo LaVie Z (the keyboard is *horrible*), with Debian Jessie, gdm3, and i3.

- Text editor: Emacs24
- Messager: Pidgin
- Web browser: Firefox Nightly (Firefox Developer Edition on occasion)
- Terminal emulator: Terminator
- Shell: bash
- Media: Banshee
- Input Method Manager: iBus
- Network manager: NetworkManager

I started Debian when I was in 9th grade, back when Squeeze was the stable. Since then I've lived with Debian, though I switched to Arch for a year (11th grade) until the 10-year-old computer that I had it running on finally died. Then I got my current system.

My first language is Ruby, then bash, HTML5+CSS3+JS, and Emacs-Lisp. I am also fluent in LaTeX (though I struggle with BibLaTeX) and can also do OpenSCAD pretty well. I can do C and Clojure to a lesser extent, and I have near-nil experience with Python and C++ (I probably did some debugging it it before!)

I can also disarm a tar bomb in under ten seconds! [[https://xkcd.com/1168/][hehe :)]]

My human languages consist of English, Japanese, Cantonese, Mandarin, and Spanish, in order of decreasing proficiency. English and Japanese I can speak, read, write, and listen at a native level. Cantonese I can speak and listen at a native level, but read at an intermediate level. Mandarin and Spanish and I speak, read, write and listen at an intermediate level.

My IB courses are English A Language and Literature SL, Spanish B SL, Economics HL, Physics HL, Math ASL (+ AP Calculus BC), and Chemistry HL. I did my Extended Essay in Computer Science, investigating solving mazes using tree-searching algorithms.

I have experience with lots of server administering, including Apache, Ruby on Rails, Minecraft, Openarena, Python SimpleHTTPServer, Tor, Squid, VPN, and VNC (I took that down though). I'm planning to learn nodejs soon.

My other passion is music. I have been playing the clarinet since 5th grade, and I obtained an Associate of Trinity College London (ATCL) Diploma. I also enjoy singing, though I am more of a clarinetist than a vocalist. I value musical expression a lot, and strongly believe that music is *a lot* more than just playing/singing the notes on the page. I like music theory as well, and can do simple composition (around 2 lines with a melody and bass line).

* About Amanokami

** Amanokami

This original Amanokami was created in 2009 by the 6th grader me. It had that nice bright blue background of #0ff, Konata in the top left corner, and a few lightout games for entertainment.

I still remember back in 7th grade when we had to make a website in computer class, I was done as soon as it was assigned.

Of course, this version of the site never went online until many years later, around 2012 when I was in 8th or 9th grade.

** Amanokami Rebooted!

I thought that the original version looked pathetic, and I was too young to figure out makefiles and Rakefiles for templating the nav bar so I got lazy and turned the whole website into one page, with CSS/JS tabs.

This version went online in 2013 when I was in 10th grade. In 2014 this version of the site was lost to DigitalOcean, because I hadn't yet learned to have a local build of the site which I push to the server. (I'm still trying to get it back!)

** Amanokami 3

Instead of perpetually having the "Under Maintenance" and "I will not have time" signs on, I finally remodeled this site yet again on January 17th, 2015 (11th grade). This place looks so much nicer now.

** Amanokami Blog

Honestly, Amanokami 3 just had too much purple, and the instant you went mobile the navibar goes all "bleh" on you. I decided to switch to a blog (that generates more content, plus I have Emacs+IB to write about) and a simpler design. Also everything is done from Emacs and Org :)

