#+TITLE:       AP Calc BC in a week - Part 5
#+AUTHOR:      Paul Elder
#+EMAIL:       paul.elder@amanokami.net
#+DATE:        2016-03-29 Tue
#+URI:         /blog/%y/%m/%d/ap-calc-bc-in-a-week-part-5
#+KEYWORDS:    ap
#+TAGS:        ap
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Learning AP Calculus BC in a week - Part 5

* Introduction
  Yay! Last day! Today is:
  - 10 Sequences and Series

  Let's start!

  This section is long so I'm going to have to split it up quite a bit...

* 10 Sequences and Series

** What is a(n) (Infinite) Sequence?

   An *infinite sequence* is a function which has the natural numbers as the domain (not including 0). It is denoted as $a_n$.

   An example of a sequence is $a_n=\frac{1}{n}$, which results in the sequence $\frac{1}{1},\frac{1}{2},\frac{1}{3}\cdots\frac{1}{n}\cdots$. $\frac{1}{n}$ is often called the _nth term_ of this sequence.

   I suppose this is to contrast sequences from the other functions that we deal with, whose domain consist of all the real numbers.

   A sequence $a$ *converges to a finite number $L$ if $\lim_{n\to\infty}a_n=L$*. If the limit does not exist then the sequence diverges.

   tl;dr A sequence is a (function) list of numbers, and if the limit ( $n\to\infty$ ) of its function is $L$, then it converges to $L$.

** What is a(n) (Infinite) Series?

   An *infinite series* is the sum of an infinite sequence.
   $$\sum_{k=1}^\infty a_k = a_1 + a_2 + a_3 + \cdots + a_n + \cdots$$
   Each element in the sum is a /term/, with $a_n$ being the _nth term_, like in the sequence.

   The series \(\sum_{k=1}^\infty a_k\) can also be written as \(\sum a_k\) or \(\sum a_n\).

   tl;dr Add all the numbers in a sequence = series

** Types of Series

   *p-series* is the series of form $$\sum_{k=1}^\infty \frac{1}{k^p}$$, where $p$ is a constant.

   *Harmonic series* is the p-series where $p=1$, ie $$\sum_{k=1}^\infty \frac{1}{k}$$

   *Geometric series* is the sum of a first term $a$ and terms of a common ratio $r$ : $$\sum_{k=1}^\infty ar^{k-1}$$

** Convergence of a Series

   If there exists a finite number $S$ such that \(\lim_{n\to\infty}\sum_{k=1}^ne a_k = S\), then the inifinite series is said to converge to $S$.

   In this case, $$\sum_{k=1}^\infty = S$$.

   tl;dr If you keep adding and it approaches a number, then the series converges to that number

   There are a couple examples of proving that series are Divergent/convergent, but... I don't think I can reproduce these with an unseen problem, since these involve finding limits of summations, so... hopefully they can be reasoned through if they do come out.

** Theorems of Convergence of Divergence

*** If \(\sum a_n\) converges, then $\lim_{n\to\infty}a_n=0$

    - By contraposition, this also means that if \(\lim_{k\to\infty}a_n\neq 0\), \(\sum a_n\) diverges
    - The converse is not true; if the limit is zero, the summation may or may not converge (if you know your truth tables this won't be a problem)
    - Note that this means that the _terms_ go to 0, not the series

*** You can add a finite number of terms to a summation without affecting its convergence/divergence

    - This means that \(\sum_{k=1}^\infty a_k\) and \(\sum_{k=m}^\infty a_k\) both converge or both diverge

*** A series can be multiplied by a nonzero constant without affecting its convergence/divergence

    - This means that \(\sum_{k=1}^\infty a_k\) and \(c\sum_{k=1}^\infty a_k\) both converge or both diverge

*** If two series converge, the sum of the two series converges

    - If \(\sum a_n\) and \(\sum b_n\) both converge, \(\sum (a_n+b_n)\) converges

*** If the terms of a convergent series are regrouped, the new series is also convergent

* Conclusion

  Uhh okay I've had this buffer open for too long I need to publish this prematurely, plus the post will become way too long anyway.

  Chapter 10 is longer than I expected... I'll have to break it up. Next time we'll be doing Tests for convergences, then after that we'll do the Power series.
