#+TITLE:       Introduction - Emacs of an IB Student
#+AUTHOR:      Paul Elder
#+EMAIL:       paul.elder@amanokami.net
#+DATE:        2016-03-01 Tue
#+URI:         /blog/%y/%m/%d/introduction
#+KEYWORDS:    emacs, ib
#+TAGS:        emacs, ib
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: First post in my blog, introducing Emacs for an IB student

* Introduction

  So I'm an IB student (well, nearing the end of it) and I like Emacs. Between my 10th and 11th grade I actually tried to prepare my computer for IB, such as the file organization, note-taking organization, Emacs organization, etc. I failed and ended up having to set it up on the way. Fun, but time-consuming, and time is a luxury as an IB student.

  Last week my computer broke, as in it refued to open any graphical programs besides Emacs, so until I fixed it (yesterday) I got to learn how to do *everything* in Emacs. This ranged from emails to Facebook messaging to scheduling (I did that in Emacs anyway) to LaTeX for all assignments to web browsing. 

  Then I remembered that every time I had to set up a new system, be it Debian or Arch or Emacs or a Ruby on Rails server or an Apache server, I keep forgetting how to do it. Even worse, internet resources are *useless* sometimes. So, I set up this blog to document problems that I solved that took hours of web searching so that I don't have to do all the web searching again! (Hopefully you won't either!)

  Also, when I searched the internet on how to organize my work directory etc etc, everything that I found was written for working people, not students, 'cause I mean what teenager uses Emacs? I had to learn a good structure for me over a year or two, and I thought that might be good to share as well, for other Emacs-using teens like me that need an idea on how to structure their work director. Same thing happened to me with scheduling and note-taking in Emacs. I had to learn on my own and here I am going to share it. 

  It's late now so I better wrap it up around here and leave the rest for next time.

* Things that I plan to write about

  - Directory Organization (General)
  - Scheduling (Emacs)
  - Note-taking (Emacs)
  - Document writing (Emacs)
  - Circular Economy (General)
  - Email, maybe (Emacs)
  - Blogging, maybe (Emacs)
  - Apache reverse proxy (Apache) 
  - Apache Rails serving (Apache)
